### ISSUE TITLE
aichat报错和临时会话报错

### ISSUE THREAD

**Issue by Kaltsit-02** [joeyHXD/aichat_chatGPT_API#11]
[报错.txt](https://github.com/joeyHXD/aichat_chatGPT_API/files/11591468/default.txt)
![B5$JQD@ 0W`CAMF%VFY_C](https://github.com/joeyHXD/aichat_chatGPT_API/assets/110442257/edf3c25b-85b9-4054-9924-e8fb29926baa)
我根据CSDN上的教程改了openai的proxy设置但是还是不行
https://blog.csdn.net/qq_40134903/article/details/129332764?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22129332764%22%2C%22source%22%3A%22weixin_44357630%22%7D&fromshare=blogdetail

**Comment by joeyHXD** [comment]
你的API key可能填错了

**Comment by joeyHXD** [comment]
invalid_api_key

**Comment by Kaltsit-02** [comment]
我尝试换了一个apikey也还是不行

**Comment by joeyHXD** [comment]
我看了你的txt，我把api故意写错后出的error和你一模一样的

**Comment by Kaltsit-02** [comment]
同一个key我使用https://github.com/Cosmos01/aichat-chatGPT这个项目的插件是可以的
但是使用本项目的插件就无法响应
![image](https://github.com/joeyHXD/aichat_chatGPT_API/assets/110442257/ff7604d0-aa20-4ba9-8ce1-d16033fb2b3f)
我这个格式应该没有问题吧

**Comment by joeyHXD** [comment]
嗯，格式看着没问题

**Comment by joeyHXD** [comment]
你的openai version是什么

**Comment by Kaltsit-02** [comment]
openai==0.27.0

**Comment by joeyHXD** [comment]
我目前用的也是0.27.0，那就怪了
要不试试pip install openai==0.26

**Comment by joeyHXD** [comment]
我看langchain那边有类似的error

**Comment by Kaltsit-02** [comment]
0.26也不行我明天尝试换个电脑部署这个项目试试吧

**Comment by joeyHXD** [comment]
https://github.com/openai/openai-python/issues/464

**Comment by Kaltsit-02** [comment]
问题莫名其妙的就解决了，今天我在水群的时候bot突然就理我了，并且没有报错，我没做任何的更改，只是昨天降级0.26任何又升级0.27后，我就关电脑了

**Comment by Kaltsit-02** [comment]
疑似是我开着全局代理就会报错，不开代理就可以用
