### ISSUE TITLE
tx现在风控了很多账号导致群聊接近瘫痪，希望可以支持私聊

### ISSUE THREAD

**Issue by yangzhan-1** [joeyHXD/aichat_chatGPT_API#13]

**Comment by joeyHXD** [comment]
这个可以有！我今晚就研究一下，有没有能参考的私聊插件？

**Comment by yangzhan-1** [comment]
https://github.com/wangyu1997/gsuidcore_plugin_chat
![image](https://github.com/joeyHXD/aichat_chatGPT_API/assets/67181805/3fcce8c7-e268-4de3-a3c7-95d94cbe6d10)

**Comment by yangzhan-1** [comment]
这个不知道算不算，你可以看看

**Comment by joeyHXD** [comment]
行

**Comment by joeyHXD** [comment]
写了一个测试私聊的功能，但是私聊应该是被风控了，虽然gocq里显示发送了但是试了很多次都完全收不到bot的私聊消息。（但群聊不会被风控）个人感觉搞私聊是死路一条捏
