### ISSUE TITLE
'ServiceFunc' object is not iterable

### ISSUE THREAD

**Issue by Gilgaladly** [joeyHXD/aichat_chatGPT_API#2]
hoshino/tool.py", line 27, in not_conflict
service_funcs.extend(t.find_handler(event))
TypeError: 'ServiceFunc' object is not iterable

这个是闲聊插件与hoshino版本不匹配吗

**Comment by joeyHXD** [comment]
我晚上测一下，这个应该是反并发的问题

**Comment by joeyHXD** [comment]
你用的是最新的hoshino吗？

**Comment by joeyHXD** [comment]
我更新到最新的hoshino了，没遇到这个问题，看了一下错误信息，应该是t.find_handler(event)返回了一个ServiceFunc object，而不是一个list，那么你可以尝试把extend改成append(错误的)

**Comment by joeyHXD** [comment]
service_funcs = []
for t in trigger.chain:
    handler = t.find_handler(event)
    if handler is not None:
        if isinstance(handler, (list, tuple)):
            service_funcs.extend(handler)
        else:
            service_funcs.append(handler)

**Comment by joeyHXD** [comment]
写成这样应该就行了

**Comment by Gilgaladly** [comment]
阿这，可能是我的版本问题哈哈哈，我去试试

**Comment by joeyHXD** [comment]
怎么样了能跑了吗？
