### ISSUE TITLE
安装依赖pip install collections 报错

### ISSUE THREAD

**Issue by miragekc** [joeyHXD/aichat_chatGPT_API#4]
安装依赖pip install collections 报错

ERROR: Could not find a version that satisfies the requirement collections (from versions: none)
ERROR: No matching distribution found for collections

换源也装不了呢

**Comment by joeyHXD** [comment]
"collections"模块是Python自带的模块，因此在安装Python（Python 2和Python 3）时会自带该模块。因此，无需安装即可使用。

**Comment by joeyHXD** [comment]
要不你先试试能不能跑？
