### ISSUE TITLE
AI概率设置不成功

### ISSUE THREAD

**Issue by WindStill** [joeyHXD/aichat_chatGPT_API#6]
使用命令“调整AI概率 10“，机器人有返回“人工智障已启用, 当前bot回复概率为10%.”
但是“当前AI概率“，还是0%

配置文件里设置默认概率，也不生效

**Comment by joeyHXD** [comment]
默认概率是指如果你的指令“调整AI概率”没有填概率的话会使用默认概率
在没有调整AI概率激活群AI的时候群AI是不会说话的
至于当前AI概率还是0%…我不清楚…我这边试了一下没问题啊，你是不是装了别的aichat插件冲突了
![Screenshot_20230322_105146_com tencent mobileqq](https://user-images.githubusercontent.com/68325229/226790105-e32726b8-22b7-4e18-9193-abaae6fdff72.jpg)

**Comment by joeyHXD** [comment]
比如说这个https://github.com/pcrbot/aichat

**Comment by WindStill** [comment]
> 比如说这个https://github.com/pcrbot/aichat

确实是装了这个ai，但是我并未开启

**Comment by joeyHXD** [comment]
那就怪了，等我晚上到家了测一下吧

**Comment by joeyHXD** [comment]
你能给我看看你的功能列表/lssv吗？

**Comment by WindStill** [comment]
> 你能给我看看你的功能列表/lssv吗？

不好意思，回复的不及时。lssv如下

```
群xxxxx服务一览：
|○| Rua
|○| _feedback_
|○| ai绘图
|○| akgacha
|○| anti-holo
|○| antiqks
|○| asill
|○| clanbattle
|○| code
|○| dice
|○| everydayNews
|○| gacha
|○| github_reminder
|○| group-leave-notice
|○| group-welcome
|○| hiumsentences
|○| image-generate
|○| pcr-arena
|○| pcr-avatar-guess
|○| pcr-cherugo
|○| pcr-comic
|○| pcr-desc-guess
|○| pcr-duel
|○| pcr-login-bonus
|○| pcr-query
|○| picfinder
|○| play_together
|○| poke-man-pcr
|○| pulipuli
|○| pulipuli-query
|○| random-repeater
|○| resou
|○| sleeping-set
|○| when2holiday
|○| wordcloud
|○| 四则运算器
|○| 头像表情包
|○| 小鸡词典
|○| 攻略
|○| 本地涩图
|○| 涩图
|○| 生草图片生成器
|○| 疫情出行政策
|○| 疫情数据
|○| 疯狂星期四
|○| 磁力搜bot
|○| 竞技场推送
|○| 群AI&chatGPT
|○| 股票查询
|○| 重开设定
|○| 随机丁真
|×| buy_potion_reminder
|×| github_reminder_poller
|×| pcr-arena-reminder-jp
|×| pcr-arena-reminder-tw
|×| pcr-midday-music
|×| pcr-news-bili
|×| pcr-news-tw
|×| 人工智障
|×| 色图打分
```

**Comment by joeyHXD** [comment]
额，你给你的bot昵称是什么

**Comment by joeyHXD** [comment]
我刚注意到，除非你改过指令，不然你这个“人工智障已启用, 当前bot回复概率为10%.”就不是我的插件…

> 使用命令“调整AI概率 10“，机器人有返回“人工智障已启用, 当前bot回复概率为10%.” 但是“当前AI概率“，还是0%
> 
> 配置文件里设置默认概率，也不生效

**Comment by joeyHXD** [comment]
总之把你人工智障的插件卸了吧…

> 我刚注意到，除非你改过指令，不然你这个“人工智障已启用, 当前bot回复概率为10%.”就不是我的插件…
> 
> > 使用命令“调整AI概率 10“，机器人有返回“人工智障已启用, 当前bot回复概率为10%.” 但是“当前AI概率“，还是0%
> > 配置文件里设置默认概率，也不生效

**Comment by joeyHXD** [comment]
或者把指令的触发词改一下

**Comment by WindStill** [comment]
好的，我试试。感谢回复

**Comment by WindStill** [comment]
我去看了下那个“人工智障”的插件，确实是命令重合了，也是”调整AI概率 N“

**Comment by joeyHXD** [comment]
因为是照着那个功能改的，想着同一个指令比较好记，改完应该就能用了，我先close了
