### ISSUE TITLE
应该是我的代理问题吧

### ISSUE THREAD

**Issue by XiaoFuOS** [joeyHXD/aichat_chatGPT_API#7]
![Screenshot_2023-03-23-00-31-18-609_com microsoft rdc android](https://user-images.githubusercontent.com/103229747/226973752-a5f2875a-6d7c-4615-83d4-da6bdb10080b.jpg)
寄力，不知道怎么办力🤣

**Comment by XiaoFuOS** [comment]
![Screenshot_2023-03-23-00-31-18-609_com microsoft rdc android](https://user-images.githubusercontent.com/103229747/226973935-ae91720a-a785-4e7c-8adf-eea08b7aaff1.jpg)
补一下图片

**Comment by joeyHXD** [comment]
这两张图片不是一样的嘛😂
估计就是代理问题了，看着有点像这个issue，你可以参考一下他们的解决办法
https://github.com/Cosmos01/aichat-chatGPT/issues/23

**Comment by XiaoFuOS** [comment]
> 这两张图片不是一样的嘛😂 估计就是代理问题了，看着有点像这个issue，你可以参考一下他们的解决办法 [Cosmos01/aichat-chatGPT#23](https://github.com/Cosmos01/aichat-chatGPT/issues/23)

网卡，看不见图片，以为没上传成功，多发了一下🤣针对这个问题应该就是代理的原因了，有推荐的机场嘛？我这几个貌似都不太稳定🤡

**Comment by joeyHXD** [comment]
你可以问问群友吧…我用的海外服务器

**Comment by XiaoFuOS** [comment]
> 你可以问问群友吧…我用的海外服务器

好嘞哥，谢了哥，知道问题所在就好解决了
